### ISSUE TITLE
大神你好，能否添加几个用MVC写View的示例

### ISSUE THREAD

**Issue by IOXBruin** [yanmingjie0223/CocosCreator#1]
大神你好，能否添加几个用MVC写View的示例
偶然在网上看到了你的框架，觉得非常不错，正在学习中。但是我初学，有很多地方不太懂。尤其是怎么具体用这套框架的MVC来写代码。能否用1-2个详细一点的例子来说明下这套框架MVC具体应该怎么写吗？感谢~

**Comment by yanmingjie0223** [comment]
有人说过同样的问题，也想过写个小游戏demo。只是一直比较忙，可能会比较晚写。可以先看看代码，尝试着用，有什么问题发邮件什么的都可以😊

**Comment by IOXBruin** [comment]
感谢回复，已经看过代码了。
1、可能是我mvc模型理解不够，架构中view的ctrl代码应该怎么写，因为代码中只是继承了一个basectrl。
2、还有就是m和c，v和c之间通信的写法有点迷茫。
3、其实不用写一个完整的demo，只要详细写一个完整的mvc流程就好，v初始化的怎么获取m的数据，m数据变化的时候怎么通知v改变显示。这个过程中c到底扮演怎样的角色，到底该怎么写。
感谢大佬写这么好的架构让我学习

**Comment by yanmingjie0223** [comment]
谢谢你的认可😊
1：mvc一般是c控制m和v的逻辑，m提供数据更新的接口，m变化通知c。v中提供界面变化的接口，v变化通知c
2：按照上面的逻辑来使用有的模块比较大会导致c特别的大显得臃肿（特别不利于维护），综合一下可以将部分逻辑拆分到m（偏向m）和v（偏向v）中。不管怎么拆分一定要保证c的控制权力，这样可以保持一个口子进就可以完成一个完整系列的功能

**Comment by IOXBruin** [comment]
感谢大佬指点迷津，我先写写试试。如果还是觉得不是很清楚，我就自己写个小Demo让大佬帮我看看改进一下。
