### ISSUE TITLE
请问可以将这个框架升级到2.4吗？

### ISSUE THREAD

**Issue by huahuacn** [yanmingjie0223/CocosCreator#2]
你好，从 v2.4 开始，Creator 正式支持 Asset Bundle 功能。
我正在使用这个框架开发游戏，然后自己升级发现搞不定。
请问你会考虑将这个框架升级到支持2.4吗？

**Comment by yanmingjie0223** [comment]
最近比较忙本来打算fgui一支持就加上的得周末了，不过可以先跑起来，不影响整体
1：StageManager中的fgui.addLoadHandler();去除
2：lib/fairygui.js 将rawBuffer修改为_buffer

**Comment by huahuacn** [comment]
谢谢。ResManager.ts里面的getRes使用的cc.loader.getRes接口在2.4没有了，我换成cc.resources.load发现没用，请问你能先帮忙看看这个吗。。。

**Comment by yanmingjie0223** [comment]
好的，已经更新到支持2.4.0了。
如果在使用中有什么问题可以讨论讨论哈，谢谢反馈

**Comment by huahuacn** [comment]
好的，感谢。
