### ISSUE TITLE
遇到两个新的问题请教一下

### ISSUE THREAD

**Issue by huahuacn** [yanmingjie0223/CocosCreator#5]
在跳转到新场景后，试图关闭前一个场景的某个界面时候出错（无论是否销毁）：
![image](https://user-images.githubusercontent.com/31203217/87880145-d8e77380-ca21-11ea-8b26-579d1de9d830.png)

跳转场景后，直接使用ViewManager.show在新场景打开新界面时报错：
![image](https://user-images.githubusercontent.com/31203217/87880133-c705d080-ca21-11ea-85f0-a53485f82647.png)

请教一下，谢谢呀。。。

**Comment by yanmingjie0223** [comment]
在App.ViewManager.close的时候默认就会消耗改界面




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanmingjie0223/CocosCreator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 凌晨0:42
收件人:&nbsp;"yanmingjie0223/CocosCreator"<CocosCreator@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[yanmingjie0223/CocosCreator] 遇到两个新的问题请教一下 (#5)





 
在关闭某个界面并试图销毁的时候出错：
 
 
跳转场景后，直接使用ViewManager.show在新场景打开新界面时报错：

**Comment by huahuacn** [comment]
就是切换新场景后使用ViewManager.close报的错误呀

**Comment by kirikayakazuto** [comment]
加个好友问吧，这样太不方便了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "mikewu"<notifications@github.com&gt;; 
发送时间: 2020年7月20日(星期一) 凌晨0:42
收件人: "yanmingjie0223/CocosCreator"<CocosCreator@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [yanmingjie0223/CocosCreator] 遇到两个新的问题请教一下 (#5)





 
在关闭某个界面并试图销毁的时候出错：
 
 
跳转场景后，直接使用ViewManager.show在新场景打开新界面时报错：

**Comment by yanmingjie0223** [comment]
上传的实例中没有出现这样的问题，这个应该是修改代码导致的
不能使用自己修改过的代码来提问题吧，这样的话就不能提issues
可以加我qq




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yanmingjie0223/CocosCreator"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月20日(星期一) 下午2:39
收件人:&nbsp;"yanmingjie0223/CocosCreator"<CocosCreator@noreply.github.com&gt;;
抄送:&nbsp;"别天神"<2386068693@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [yanmingjie0223/CocosCreator] 遇到两个新的问题请教一下 (#5)





 
就是切换新场景后使用ViewManager.close报的错误呀
